name: Release

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run tests
      run: |
        git remote add upstream https://github.com/stuttter/ludicrousdb.git
        git fetch
        git describe
        # version=$(git describe upstream/master --abbrev=0)
        # version=${version:-"current"}
        # echo "Building with version: [${version}]"
        # ahead=$(git rev-list --count upstream/master...master)
        # ahead=${ahead:-"beta"}
        # echo "Building ahead: [${ahead}]"
        # zipname="ludicrousdb-wpmudev-${version}-${ahead}.zip"
        # echo "Building zipname: [${zipname}]"
        # git archive --format=zip --prefix=ludicrousdb/ -o $zipname HEAD $(ls --color=none | grep -v 'tests')
        # ls -lah
